# Welcome to Jekyll!

# Site settings
title: Neil Charlton | 
email: neil@bleepsystems.com
description: Making Stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

sass:
  style: nested
  #style: compressed

gems: [bourbon,neat]

#permalink: pretty
permalink: /:year/:title.html

collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/