# Welcome to Jekyll!

# Site settings
title: Find a Financial Advisor
email: neil@bleepsystems.com
description: > # Static site generator for Elmwood
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

sass:
  style: compressed

gems: [bourbon,neat]